baseURL = "https://hat.thatteidlikaalsoup.team/"
languageCode = "en-us"
title = "Ultimate Frisbee Hat"
theme = "alpha-church"

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# Paramaters for the whole site
[params]
  title = "Ultimate Frisbee Hat"
  subtitle = "Beginner's Ultimate Frisbee Hat"
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp

  # bible_popups = "faithlife" #faithlife, blb
  # bible_version = "CSB" #HCSB, NIV, NLT, ESV, etc.
  # instant_page = false

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps or "google"
    # For Open Street Map widgets
    latitude = "12.9385184"
    longitude = "77.5894409"
    zoom = "18"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""


    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    [[params.links]]
      service = "Instagram"
      icon = "fa-instagram"
      icon_pack = "fab"
      link = "//instagram.com/thatteidlikaalsoup"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//www.facebook.com/Thatteidlikaalsoup/"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
